### ISSUE TITLE
input file discretization

### ISSUE THREAD

**Issue by MelissaCastellan** [peridigm/peridigm#378]
I'm trying to do a simulation, but I can't figure out what input file peridigm needs, or rather it needs a .yaml file and a discretization file. How can I create the discretization file, because it says to use Cubit but I'm using other programs to generate the meshes of my geometry, but whatever format I use the program tells me that it is not valid, are there any alternatives to using Cubit?

The error that Peridigm gives me is the following: -- Peridigm -- version 1.5.0 (Dev) Error! The "Input Mesh File" parameter does not exist in the (sub)list of "Peridigm->Discretization" parameters.

The current parameters set in the "Peridigm->Discretization" (sub)list are:

{
"Type" : string = Exodus
"Input Mesh" : string = Cubo.stl
"Influence Function" : string = One
}

Throw number = 1

Wallclock Time (seconds):
Total 0.016

**Comment by oldninja** [comment]
Hi @MelissaCastellan , Peridigm needs a *.yaml file as the input file for the simulation and it needs a discretization file to create the domain, it can be a meshed model from Cubit or it can be a text file.
For the case of a meshed model in Cubit, take a look at: 
- examples/disk_impact/disk_impact.yaml   --> Peridigm's input file
- examples/disk_impact/disk_impact.jou      --> Journal file for Cubit
- examples/disk_impact/disk_impact.g         --> Cubit mesh file

For the case of a text file, take a look at: 
- examples/fragmenting_cylinder/fragmenting_cylinder.yaml                         --> Peridigm's input file
- examples/fragmenting_cylinder/fragmenting_cylinder_generate_mesh.py   --> Python script to generate the collocation points
- examples/fragmenting_cylinder/fragmenting_cylinder.txt                             --> Text file for the "mesh"

**Comment by johntfoster** [comment]
You should be able to use alternative mesh generators and then use meshio
<https://github.com/nschloe/meshio> to convert it to a Genesis/Exodus file.
The input files should have a “.g” file extension. Alternatively, you can
specify the node locations and volumes and use a “text file
discretization”.

In order to use the yaml input files, you need to make sure that Trilinos
is built with yaml support turned on.

Finally, one of the best ways to dig into the not-so-well documented
features of Peridigm is to look at the tests that are shipped with the
source code.

**Comment by djlittl** [comment]
In addition to what John said, you can also use a simple text file as input for the mesh file.  Examples can be found in the test suite.  Those files have .txt file extensions.

Dave

From: John T. Foster ***@***.***>
Date: Thursday, October 17, 2024 at 10:08 AM
To: peridigm/peridigm ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] Re: [peridigm/peridigm] input file discretization (Issue #378)
You should be able to use alternative mesh generators and then use meshio
<https://github.com/nschloe/meshio> to convert it to a Genesis/Exodus file.
The input files should have a “.g” file extension. Alternatively, you can
specify the node locations and volumes and use a “text file
discretization”.

In order to use the yaml input files, you need to make sure that Trilinos
is built with yaml support turned on.

Finally, one of the best ways to dig into the not-so-well documented
features of Peridigm is to look at the tests that are shipped with the
source code.

**Comment by MelissaCastellan** [comment]
Thanks for your reply, but I have installed meshio and I'm trying to use
meshio to convert mesh files from .vtk to .exo format but I get this error:

 meshio.write("/home/melissa/bilanciere/Cubo.exo ", mesh) Traceback (most
latest call last ): File "", line 1, in File
"/home/melissa/.local/lib/python3.6/site-packages/meshio/_helpers.py", line
141, writing return writer(filename, mesh, **kwargs) File
"/home/melissa/.local/lib/python3.6/site-packages/meshio/exodus/_exodus.py",
line 263, writing with netCDF4.Dataset( filename, "w") as rootgrp: File
"src/netCDF4/_netCDF4.pyx", line 2463, in netCDF4._netCDF4.Dataset.init
File "src/netCDF4/_netCDF4.pyx", line 2026, in
netCDF4._netCDF4._ensure_nc_success OSError: [Errno -101] NetCDF: HDF
error: b'/home/melissa/balancer /Cubo. exo'


On the other hand, it creates other formats like .stl without problems.

Il giorno gio 17 ott 2024 alle ore 19:03 David Littlewood <
***@***.***> ha scritto:

**Comment by franciscoyapor** [comment]
Try setting the environment variable to false:
`os.environ['HDF5_USE_FILE_LOCKING']='FALSE'`

**Comment by MelissaCastellan** [comment]
Thanks for your reply but it still gives me the following error:

Peridigm asta.yaml

-- Peridigm
-- version 1.5.0 (Dev)

/home/melissa/peridigm/src/io/discretization/Peridigm_ExodusDiscretization.cpp:1104:

Throw number = 1

Throw test that evaluated to true: 1

PeridigmNS::OutputManager_ExodusII::ExodusDiscretization::loadData()() --
Error code: -1 (ex_get_elem_attr)
Wallclock Time (seconds):
  Total            0.049


would you know how to solve it?

Il giorno lun 21 ott 2024 alle ore 16:28 Francisco A. Yapor Genao <
***@***.***> ha scritto:

**Comment by franciscoyapor** [comment]
Can you share the *.yaml file and the Cubo.exo file so that I can take a look at them? Maybe a link to a shared drive...

**Comment by MelissaCastellan** [comment]
Thanks, I leave the .yaml file and the .exo file attached

Il giorno dom 3 nov 2024 alle ore 22:51 Francisco A. Yapor Genao <
***@***.***> ha scritto:

**Comment by MelissaCastellan** [comment]
This is the link drive

https://drive.google.com/drive/folders/1b_Pqi2sa-ovIzTiMOOnlYvdjjBxE5Xub?usp=drive_link


where there is the mesh file

Il giorno lun 4 nov 2024 alle ore 09:47 Melissa Castellan <
***@***.***> ha scritto:

**Comment by jritta** [comment]
Hi @MelissaCastellan,

One problem for sure is that you have geometrical entities, like points, lines, and surfaces, in your input discretization `asta.e` that can't be processed by peridigm. If the volume elements with the block id `Block 26` can be processed I am not sure at the moment. What definitely works are hex and tetra elements. Those get internally converted to sphere elements with the corresponding mass and center of gravity.
Furthermore, the `Numerical Methods` is not a valid Keyword in standard Peridigm. The whole section
```yaml
  Numerical Methods:
    Type: "Local"
    Integrator: "Forward Euler"
    Time Step: 0.01
    Max Iterations: 100
```
isn't and
```yaml
  Load:
     Vertical Force:
     Type: "Force Density"
     Node Set: "top_surface"
     Coordinate: "y"
     Value: -10.0

  Node Sets:
  left_end: [0, 1, 2, 3, 44]
  right_end: [9, 18, 27, 36]
  top_surface: [2, 3, 6, 7, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 52, 53, 54, 55, 56, 57]
```
this I don't know what it should be?

I suggest you to adapt the example [ElasticBondBased3D](https://github.com/peridigm/peridigm/blob/master/test/verification/ElasticBondBased/ElasticBondBased3D/ElasticBondBased3D.yaml) with your input discretization as a starting point and then keep adding complexity step by step... In this example you can even delete the Compute Class Section so the yaml file would look like:
```yaml
Peridigm:

  Discretization:
      Type: "Exodus"
      Input Mesh File: "ElasticBondBased3D.g"

  Materials:
      My Elastic Bond Based Material:
          Material Model: "Elastic Bond Based"
          Density: 7800.0
          Bulk Modulus: 200.0e9

  Blocks:
      My Group of Blocks:
          Block Names: "block_1 block_2 block_3"
          Material: "My Elastic Bond Based Material"
          Horizon: 0.751

  Boundary Conditions:
      Prescribed Displacement X:
          Type: "Prescribed Displacement"
          Node Set: "nodelist_1"
          Coordinate: "x"
          Value: "0.0"
      Prescribed Displacement Y:
          Type: "Prescribed Displacement"
          Node Set: "nodelist_1"
          Coordinate: "y"
          Value: "0.001*y*t/1.0e-8"
      Prescribed Displacement Z:
          Type: "Prescribed Displacement"
          Node Set: "nodelist_1"
          Coordinate: "z"
          Value: "0.0"

  Solver:
      Verbose: false
      Initial Time: 0.0
      Final Time: 1.0e-8
      Verlet:
        Fixed dt: 2.0e-9

  Output1:
      Output File Type: "ExodusII"
      Output Filename: "ElasticBondBased3D"
      Output Frequency: 1
      Output Variables:
          Volume: true
          Displacement: true
          Velocity: true
          Force: true
          Number_Of_Neighbors: true

```
There you need to adapt the block ID, the node sets for BCs and the input discretization. As a node set you maybe provide a list of the nodes for each BC and then call it in the input deck as e.g.
```yaml
   Boundary Conditions:
      Node Set My First Set: "My_first_node_set.txt"
      Prescribed Displacement X:
          Type: "Prescribed Displacement"
          Node Set: "Node Set My First Set"
          Coordinate: "x"
          Value: "0.0"
```
In Peridigm the nodes are counted from 1, so there is not node with the ID 0! Therefore the node set file `My_first_node_set.txt` would maybe look like
```
6
9
2
45
5
```
When the nodes with the IDs 6, 9, 2, 45, 5 are part of the boundary condition `Prescribed Displacement X` in your input deck.

Good luck!

Best,
J
